name: bertron
channels:
- defaults
dependencies:
- python=3.8
- jupyter==1.0.0
- matplotlib==3.4.1
- numpy
- pandas==1.2.4
- pyarrow==4.0.0
- scikit-learn==0.24.1
- scipy==1.6.3
- sklearn==0.0
- tokenizers==0.10.2
- toolz==0.11.1
- torch==1.8.1
- tqdm==4.60.0
- transformers==4.5.1
- pip==21.0.1

